export default {
  USER_CREATED: 'User created successfully',
  UNAUTHORIZED: 'Unauthorized access',
  MISSING_FIELDS: 'Required fields are missing',
  USERS_FETCHED: 'Users fetched successfully',
  AUTH_TOKEN_REQUIRED: 'Authorization token are required',
  AUTH_TOKEN_INVALID: 'Authoization token are Invalid',
  ALREADY_REGISTERED: 'User already registered',
  NOT_FOUND: 'User Not found',
  INVALID_CREDENTIALS: 'Invalid email password or Id',
  LOGIN: 'login Successfully',
  UPDATE: 'Update Successfully',
  OTP: 'Otp send Successfully on your email',
  OTP_VERIFY: 'OTP Verify Seccessfully',
  INVALID_OTP: 'Invalid or expired OTP',
  PASSWORD: 'New password must be different from the old password',
  GEMINAI: 'created successfully',
  SUCCESSFULLY: 'Send successfully',
};
